import Vue from 'vue'


Vue.prototype.$states = [
        	{value:'FC', show:'Abuja'},
			{value:'AB', show:'Abia'},
			{value:'AD', show:'Adamawa'},
			{value:'AK', show:'Akwa Ibom'},
			{value:'AN', show:'Anambra'},
			{value:'BA', show:'Bauchi'},
			{value:'BY', show:'Bayelsa'},
			{value:'BE', show:'Benue'},
			{value:'BO', show:'Borno'},
			{value:'CR', show:'Cross River'},
			{value:'DE', show:'Delta'},
			{value:'EB', show:'Ebonyi'},
			{value:'ED', show:'Edo'},
			{value:'EK', show:'Ekiti'},
			{value:'EN', show:'Enugu'},
			{value:'GO', show:'Gombe'},
			{value:'IM', show:'Imo'},
			{value:'JI', show:'Jigawa'},
			{value:'KD', show:'Kaduna'},
			{value:'KN', show:'Kano'},
			{value:'KT', show:'Katsina'},
			{value:'KE', show:'Kebbi'},
			{value:'KO', show:'Kogi'},
			{value:'KW', show:'Kwara'},
			{value:'LA', show:'Lagos'},
			{value:'NA', show:'Nassarawa'},
			{value:'NI', show:'Niger'},
			{value:'OG', show:'Ogun'},
			{value:'ON', show:'Ondo'},
			{value:'OS', show:'Osun'},
			{value:'OY', show:'Oyo'},
			{value:'PL', show:'Plateau'},
			{value:'RI', show:'Rivers'},
			{value:'SO', show:'Sokoto'},
			{value:'TA', show:'Taraba'},
			{value:'YO', show:'Yobe'},
			{value:'ZA', show:'Zamfara'},
        ];
Vue.prototype.$naira = '₦';